build:
    environment:
        php:
            version: "7.2"
    project_setup:
        before:
            - "composer install"
    nodes:
        analysis:
            cache:
                directories:
                - vendor/