language: php
php:
  - 7.2
  - 7.3

git:
  depth: 1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --no-interaction
  - echo "CLIENT_ID=$CLIENT_ID" >> .env.test.local
  - ls -la
  - cat .env.test.local
  - pwd

script:
  - php bin/phpunit --coverage-clover=clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
