token_generate:
    path: /token/generate
    controller: App\Component\Token\Communication\Controller\Token::generate
token_save:
    path: /token/save/
    controller: App\Component\Token\Communication\Controller\Token::saveToken